### PR TITLE
Add config mapping tcf purposes to airgap

### PR DESCRIPTION
**Pull request by anotherminh**
## Related Issues

- Closes https://transcend.height.app/T-31385

## Security Implications

_[none]_

## System Availability

_[none]_

### CODE REVIEW

**Review by linh-transcend — APPROVED** [review]

**Comment by csmccarthy** [comment]
Question: as far as I can tell this would be going onto the tcf load options object, which would also end up getting bundled in with airgap core, is that right? If that's the case, would we want to use the new bundledModuleData design? It's definitely a module-specific object, might be worth considering

**Comment by anotherminh** [comment]
@csmccarthy yea it is... i was hesitant to change this now bc we're pressed for time but let me look into it.

**Comment by csmccarthy** [comment]
> @csmccarthy yea it is... i was hesitant to change this now bc we're pressed for time but let me look into it.

@anotherminh Totally get that, just thought I'd bring it up since I know bundle size is always a concern of ours. Lmk if you want to huddle on it or if you want me to take a crack at anything

**Comment by anotherminh** [comment]
Closing this in favor of https://github.com/transcend-io/consent-manager-tcf-ui/pull/45

**Pull request closed without merging**
