### PR TITLE
New view state: PrivacyPolicyNoticeWithCloseButton

### PR DESCRIPTION
**Pull request by michaelfarrell76**
## Related Issues

- links https://transcend.height.app/T-30875

### CODE REVIEW

**Review by eligrey — DISMISSED** [review]
I guess it's too late for PrivacyPolicyNoticeWithCloseButton? PrivacyPolicyNoticeWithX is fine but it could be a tad more semantic

**Comment by michaelfarrell76** [comment]
@eligrey not too late - doing now!

**Review by eligrey — APPROVED** [review]

**Review by banzzai — APPROVED** [review]

**Comment by banzzai** [comment]
That's mostly just the version bump here, right

**Comment by michaelfarrell76** [comment]
@banzzai yes - and i added the new view state to the enum definition defining all of the view states

**Pull request merged**
