### PR TITLE
Export experience.ts from index file

### PR DESCRIPTION
**Pull request by bencmbrook**
## Related Issues

- _[none]_

## Security Implications

_[none]_

## System Availability

_[none]_

### CODE REVIEW

**Comment by bencmbrook** [comment]
Currently importing like so Screenshot 2023-11-13 at 2 35 03 PM

**Review by csmccarthy — APPROVED** [review]
Oh I totally missed this with the code cleanup, thank you !!

**Comment by csmccarthy** [comment]
Oh don't forget to bump the package version also

**Review by csmccarthy — APPROVED** [review]
Looks good, ty ty

**Pull request merged**
