### PR TITLE
Adds new view state OptOutDisclosure

### PR DESCRIPTION
**Pull request by michaelfarrell76**
1 click opt out of all consent purposes allowed in a regime

## Related Issues

- links https://transcend.height.app/T-22839

### CODE REVIEW

**Review by MadDataScience — APPROVED** [review]
Not totally clear on what a response view state is

**Review by karleyskill — APPROVED** [review]

**Comment by michaelfarrell76** [comment]
@MadDataScience the difference is that these view states cant be selected in the experiences ui for auto prompting

**Comment by MadDataScience** [comment]
> the difference is that these view states cant be selected in the experiences ui for auto prompting

@michaelfarrell76 so when _would_ they appear?

**Comment by michaelfarrell76** [comment]
@MadDataScience it would happen when they use the sdk to open the modal, same way the DoNotSellDisclosure works

**Comment by MadDataScience** [comment]
> it would happen when they use the sdk to open the modal, same way the DoNotSellDisclosure works

(I'm not sure how DoNotSellDisclosure works either, TBH. I just know it was removed from initial view states.) Sorry, I know this is all very basic. I'm just wondering about the use case of someone using the SDK to open the modal. (I was imagining the customer would tie that to a button for the user to click, but that's just a guess.)

**Comment by MadDataScience** [comment]
> but because these view states opt the user out immediately upon opening the modal, rather than after a separate button interaction, these view states cannot be used with auto-prompt because the auto prompt would just opt every user out

I think I see. I notice these are both "disclosures". Based on what you said, I take it that means these do not provide options, but simply explain what the user just agreed to?

**Comment by michaelfarrell76** [comment]
@MadDataScience yes exactly

**Pull request merged**
